# R2Devops.io pipeline template - this template aims to generate a complete pipeline
#
# Inputs:
#   - List of technologies detected in the project : dockerfile, html, markdown, yaml,

name: R2Devops
on:
  push:
    branches: [ master,r2devops-autopipeline]
  pull_request:
    branches: [ master ]

jobs:

